### PR TITLE
PP-1521: Turn on snmp so metrics can be scraped

### PR DESCRIPTION
**Pull request by whpearson**
### Description

It only allows localhost to access it. Which is
the probably the most common use case (with collectd/
telegraf).

### Issues Resolved

[List any existing issues this PR resolves]

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by whpearson** [comment]
I need to bump the version. I'd be tempted to rebase off v3.0.0 which fixes the squid version in a more elegant way but then we are stuck using our fork? @bazbremner, is there a reason why we've not tried started to use upstream.

**Comment by bazbremner** [comment]
I just hadn't got that far. Feel free to do whatever makes sense now.

**Comment by whpearson** [comment]
I'm going on support tomorrow. So best to try and get everything in good order rather than trying to fix things properly.

**Comment by joshmyers** [comment]
Just checking that 60a545cb6a386a0feef15294d3463b115d85cff7 was supposed to be in this PR?

**Comment by whpearson** [comment]
Yup. It is this branch, ubuntu_package_version_lookup that never got merged and is the one currently being used. 

See https://github.com/alphagov/pay-chef/blob/master/Berksfile#L8

Sorry should have commented when I pushed it on there.

**Comment by joshmyers** [comment]
LGTM 👍

**Pull request merged**
